First try
htmlacademy-php/1525665-yeticave-12 pull request #10
Opened 2020-08-01 14:13 UTC by IlyaPer

2020-08-03 04:37 UTC, nkolosov requested changes

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +CREATE UNIQUE INDEX user_id on users(id);
Если создан `PRIMARY KEY` дополнительного индекса на это поле не нужно. а вот на `email` - надо

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  description TEXT(128) not null,
TEXT поле без ограничений по длине

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  image FILE,
Нет, файл целиком в БД храниться не будет, а будет храниться URL до него на сервере, это будет текстовое поле

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  winner CHAR(64) not null,
Пока идет аукцион победитель не известен, так что там будет храниться NULL

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  category_id CHAR(64)
categories.id - это INT, а тут CHAR, что не будет корректно работать, здесь нужно построить внешний ключ

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  id INT AUTO_INCREMENT PRIMARY KEY,
Не хватает связки, к какому лоту ставка и кто её сделал

2020-08-03 04:37 UTC, nkolosov commented on schema.sql
> +  cat_name CHAR(50) not null,
Префиксы к полям - лишние, это и так видно по названию таблицы

2020-08-04 04:42 UTC, nkolosov requested changes

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +USE YetiCave;
Тут БД отличается от той, что создано (`yeticave` и `YetiCave`)

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  name CHAR(64),
Имя обязательно

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  email VARCHAR(128),
email может быть длиннее 128 символов (и это тоже обязательное поле)

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  contacts CHAR(64),
Контакты лучше сделать полем типа `TEXT`, кроме того оно также обязательно

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  password CHAR(64)
Пароль - тоже обязательное поле

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  author CHAR(64) not null,
В полях "автор" и "победитель" для лота будет храниться их ID соответствующего пользователя, он должен совпадать по типу данных с ними

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +CREATE INDEX lots_desc on lots(description);
Для полей типа `TEXT` должен быть полнотекстовый индекс

2020-08-04 04:42 UTC, nkolosov commented on schema.sql
> +  author CHAR(64) not null,
Кроме того, для таких полей нужно задавать внешний ключ

2020-08-04 08:58 UTC, IlyaPer commented on schema.sql
> +  contacts TEXT not null,
Если индексы необходимы для поиска лотов, то наверное здесь нет необходимости в использовании индекса, так как вряд ли кто-то будет искать лот по контактам.

2020-08-04 10:30 UTC, nkolosov requested changes

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  contacts TEXT not null,
Верно, индекс тут и не нужен

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  register_date DATETIME not null;
А ты пробовал этот SQL запустить? Тут ошибка

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  email VARCHAR not null UNIQUE,
Ошибка, для VARCHAR обязательно указание максимальной длины. Просто 128 для email это мало, согласно спецификации он может содержать до 320 символов
https://remoteshaman.com/programming/common/rfc-the-best-guide-to-standards

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  image URL CHAR(100),
Нет типа данных `URL` в MySQL

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  author not null,
Тип данных нужно указать, он должен совпадать с типом данных в поле `id` в таблице `users`

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +ALTER TABLE users ADD
Наоборот, внешний ключ создается для таблицы `lots` и ссылается на таблицу `users`

2020-08-04 10:30 UTC, nkolosov commented on schema.sql
> +  user_id INT,
Аналогично, `user_id` и `lot_id` обязательны и должны являться внешним ключом

2020-08-05 05:07 UTC, nkolosov requested changes

2020-08-05 05:07 UTC, nkolosov commented on schema.sql
> +REFERENCES users
Лот должен ссылаться уже не на юзера, а на лоты

2020-08-05 05:07 UTC, nkolosov commented on schema.sql
> +CREATE UNIQUE INDEX bets_id on bets(id);
Если поле является PRIMARY KEY, то дополнительных индексов не надо

2020-08-05 08:29 UTC, nkolosov requested changes

2020-08-05 08:29 UTC, nkolosov commented on schema.sql
> +REFERENCES lots
Здесь всё было правильно, user_id ссылается на таблицу users
А lot_id ссылается на таблицу lots

2020-08-05 08:29 UTC, nkolosov commented on schema.sql
> +  category_id INT not null
Что-то я пропустил это при предыдущих проверках.
Нужна таблица для категорий и, соответственно, foreign key на это поле

2020-08-05 09:17 UTC, merged