Module4 task2
htmlacademy-php/1525665-yeticave-12 pull request #11
Opened 2020-08-10 07:39 UTC by IlyaPer

2020-08-10 07:52 UTC, IlyaPer commented on queries.sql
> +SELECT name, first_price, url, first_price + bet_step FROM lots JOIN categories; --
Здесь неуверен насчет того, может ли быть значение в виде суммы значений из разных столбцов.

2020-08-10 07:55 UTC, IlyaPer commented on queries.sql
> +UPDATE lots SET name = '2014 Rossignol District Snowboard'  id = '1';--
В задании не совсем понятно сформулировано: нужно изменить определенное название лота или любое?

2020-08-10 10:34 UTC, nkolosov requested changes

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +INSERT INTO categories (name) VALUES ('Доски и лыжи' 'Крепления' 'Ботинки' 'Одежда' 'Инструменты' 'Разное');
Этот запрос не рабочий

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +INSERT INTO lots (date_creation, name, description, url, first_price, date_delection, bet_step, author, winner, category_id) VALUES (
Этот запрос тоже не рабочий

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +INSERT INTO bets (time_bet, cost, user_id, lot_id) VALUES(
Аналогично, не рабочий.

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +SELECT name FROM categories; -- Получил все категории
Здесь ты получил только названия категорий, а нужно получить и другие данные (например, иконку категории)

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +SELECT name, first_price, url, first_price + bet_step FROM lots JOIN categories; --
Выполни этот запрос у себя локально и проверь :)

Так можно, но у меня вопрос: "А что ты хочешь получить таким образом, какие данные?", "начальная цена + шаг аукциона" зачем нужны?

2020-08-10 10:34 UTC, nkolosov commented on queries.sql
> +UPDATE lots SET name = '2014 Rossignol District Snowboard'  id = '1';--
Любое, запросы нужно написать для того, чтобы потом, в дальнейших заданиях брать их в качестве примера и заменять какие-то значения на использование переменных в коде

2020-08-14 16:44 UTC, nkolosov requested changes

2020-08-14 16:44 UTC, nkolosov commented on queries.sql
> +SELECT categories.name, lots.name, first_price, url, bet_step FROM lots JOIN categories ON categories.id = lots.category_id;
Задание 
получить самые новые, открытые лоты. Каждый лот должен включать название, стартовую цену, ссылку на изображение, текущую цену, название категории;

Не хватает условия "открытые лоты", тут ты получил просто все лоты

2020-08-14 16:44 UTC, nkolosov commented on queries.sql
> +SELECT cost FROM bets ORDER BY time_bet DESC;
Здесь нужно получить ставки конкретного лота, а не всех. Нужно добавить условие на идентификатор

2020-08-19 08:28 UTC, IlyaPer commented on queries.sql
>  SELECT categories.name, lots.name, first_price, url, bet_step FROM lots JOIN categories ON categories.id = lots.category_id WHERE date_delection > NOW();
Добавил условие,  которое "не пропускает" закрытые лоты

2020-08-19 08:38 UTC, nkolosov requested changes

2020-08-19 08:38 UTC, nkolosov commented on queries.sql
>  SELECT categories.name, lots.name, first_price, url, bet_step FROM lots JOIN categories ON categories.id = lots.category_id WHERE date_delection > NOW();
"получить самые новые, открытые лоты. Каждый лот должен включать название, стартовую цену, ссылку на изображение, текущую цену, название категории;"

Где текущая цена?

2020-08-19 08:38 UTC, nkolosov commented on queries.sql
> +SELECT cost FROM bets ORDER BY time_bet DESC WHERE id = 3;
"получить список ставок для лота по его идентификатору с сортировкой по дате."

Во-первых, запрос не работает.
Во-вторых, стоит получить все поля, а не только цену

2020-08-25 14:26 UTC, merged