Module6 task2
htmlacademy-php/1525665-yeticave-12 pull request #14
Opened 2020-09-13 07:11 UTC by IlyaPer

2020-10-15 06:05 UTC, IlyaPer commented on function.php
> + function validateImage($file){
Вот тут есть вопрос. Вроде никаких ошибок не выдает, а ошибку в массиве errors не видит, хотя функция возвращает необходимые ошибки.

2020-10-15 06:06 UTC, IlyaPer commented on function.php
> +  elseif (!is_numeric($price)) {
тут также трудность: даже если я ввожу целое число, выдает ошибку `"Это поле должно быть заполнено числом"`

2020-10-15 06:11 UTC, IlyaPer commented on templates/add.php
> +        <?php if (isset($errors['date_delection'])){
Здесь аналогичная проблема с вариацией фото: ошибка не высвечивается

2020-11-10 10:30 UTC, nkolosov requested changes
Ещё в репозиторий попали твои файлы из папки uploads, содержимое этой папки стоит добавить в .gitignore

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +if ($_SERVER['REQUEST_METHOD'] == 'POST') {
Везде нужно использовать строгое сравнение `===`

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +           $result = $rules[$key];
Кажется, что `$result` - ненужная переменная

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +             $errors[$key] = $rule($value);
Дважды вызывается `$rule($value)`

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +         $errors[$key] = $rule($value);
Также, дважды вызывается одно и тоже

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +     if (isset($rules[$key]) && $rules[$key] !== null) {
Если `isset($rules[$key]) === true`, то всегда `$rules[$key] !== null`

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +          move_uploaded_file($_FILES['lot-img']['tmp_name'], $file_path);
Нужно проверить, что операция выполнилась успешно

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +      $lot = $_POST;
Выше в коде уже есть такое присваивание.
И в любом случае, непонятно, где используется `$lot` и для чего

2020-11-10 10:30 UTC, nkolosov commented on add.php
> +          $safe_title = mysqli_real_escape_string($connection, $_POST['title']);
Как-то странное получается, что часть полей обрабатывается через `mysqli_real_esccape_string`, а часть - нет.
Ну и в любом случае, эта логика уже есть в db_get_prepare_stmt, не нужно её дублировать

2020-11-10 10:30 UTC, nkolosov commented on function.php
> + function validateImage($file){
Ну, во-первых, не очень понятно зачем в функцию передается `$file`, если эта переменная затем нигде внутри функции не используется.

Во-вторых, эта функция всегда возвращает `false`, хотя по идее в случае успеха должно возвращаться `true`

2020-11-10 10:30 UTC, nkolosov commented on function.php
> +function validatePrice($price){
Здесь и в других местах: значение передается аргументом (`$price`) но при этом внутри функции никак не используется

2020-11-10 10:30 UTC, nkolosov commented on init.php
> +  $link = mysqli_connect("localhost", "root", "", "yeticave");
Зачем это? Выше же уже создается коннект

2020-11-10 10:30 UTC, nkolosov commented on templates/add.php
> +  <form class="form form--add-lot container" action="add.php" method="post" enctype="multipart/form-data"> <!-- form--invalid -->
Если есть ошибки, форме должен добавиться класс form-invalid

2020-11-17 10:49 UTC, nkolosov requested changes

2020-11-17 10:49 UTC, nkolosov commented on add.php
> +         $errors[$key] = $rule($value);
Проблема никуда не исчезла

2020-11-17 10:49 UTC, nkolosov commented on add.php
> +          move_uploaded_file($_FILES['lot-img']['tmp_name'], $file_path);
Проблема никуда не исчезла, только теперь эта функция ещё и дважды вызывается, при этом в случае ошибки, исполнение кода продолжается

2020-11-17 10:49 UTC, nkolosov commented on init.php
> +  session_start();
Это нужно дальше в заданиях, здесь это не нужно

2020-11-17 10:49 UTC, nkolosov commented on templates/add.php
> +      <textarea id="description" name="description" placeholder="Напишите описание лота" value="<?= htmlspecialchars(getPostVal('description')); ?>"></textarea>
Значение в `textarea` передается не через `value`, поэтому в случае ошибки данные теряются =(

2020-11-17 10:49 UTC, nkolosov commented on templates/add.php
> +        <input class="form__input-date" id="date_delection" type="text" name="date_delection" placeholder="Введите дату в формате ГГГГ-ММ-ДД" value="<?= htmlspecialchars(getPostVal('date_delection'))
В вёрстке у этого поля при клике отображается календарь, у тебя его нет, нужно сделать

2020-11-17 10:51 UTC, nkolosov requested changes

2020-11-17 10:51 UTC, nkolosov commented on add.php
> +   $link = mysqli_connect("localhost", "root", "", "yeticave");
Коннект уже создается в `init.php`

2020-11-17 10:51 UTC, nkolosov commented on function.php
> +function validateEmail($name) {
Для всех самописных функций нужно указывать параметры аргумента и возвращаемого значеия

2020-12-19 01:16 UTC, nkolosov reviewed
В репозитории не должно быть файлов из директории `uploads`, не нужно добавлять их в репозиторий

2020-12-19 01:27 UTC, nkolosov requested changes

2020-12-19 01:27 UTC, nkolosov commented on add.php
> +
Лишняя пустая строка.

Ну и в целом стоит отформатировать код, чтобы отступы везде были одинаковые

2020-12-19 01:27 UTC, nkolosov commented on add.php
> +        return $move_foto;
Это не функция, куда и зачем возвращается значение?

2020-12-19 01:27 UTC, nkolosov commented on add.php
> +      $move_foto = move_uploaded_file($_FILES['lot-img']['tmp_name'], $file_path);
Слова `foto` нет, транслит не используем в коде.

Кроме того, название переменной должно отражать что в ней содержится, здесь больше подойдет `file_upload_result`, например

2020-12-19 01:27 UTC, nkolosov commented on function.php
> +  elseif (ctype_digit(($_POST['first_price'])) === FALSE && $_POST['first_price'] != '0') {
Константы `true`/`false`/`null` именуются в нижнем регистре

2020-12-19 01:27 UTC, nkolosov commented on function.php
> +  elseif (ctype_digit(($_POST['first_price'])) === FALSE && $_POST['first_price'] != '0') {
Кроме того, везде используем строгое сравнение `===`/`!==`

2020-12-21 18:03 UTC, nkolosov commented on add.php
> +             $lot['lot-img'] = "Ошибка загрузки фото!";
Если произошла ошибка, то не надо пытаться сохранить что-то в БД

2020-12-21 18:06 UTC, nkolosov commented on add.php
> +         if(validatePrice('first_price') === false){
Здесь в функцию передается аргумент, а в самой функции он не используется.
Стоит сделать функцию `validatePrice` аналогичной остальным функциям валидации

2020-12-21 18:06 UTC, nkolosov commented on add.php
> +        if(validateBet('bet_step') === false){
Аналогично функции проверки цены

2020-12-28 11:01 UTC, nkolosov commented on add.php
> +             exit;
Здесь произойдет выход из скрипта, и ошибка пользователю не выведется

2021-01-13 10:56 UTC, nkolosov commented on add.php
> +            $lot['url'] = $file_path;
Это значение нигде не используется дальше, зачем это присваивание?

2021-01-13 10:58 UTC, nkolosov commented on function.php
> +  elseif (ctype_digit($price) === false && $price !== '0') {
Блок `else` не нужен
Можно оставить так
```
if (...) {
   return false;
}

if (...) {
  return false;
}

return true;
```

2021-01-13 10:59 UTC, nkolosov commented on function.php
> +  elseif (ctype_digit($price) === false && $price !== '0'){
Аналогично тому, что я написал выше.

Кроме того, это копипаст функции `validatePrice`, и хотя функция `validateBet` внутри используется переменная `$price` (правильнее использовать `$bet`)

2021-01-13 11:00 UTC, nkolosov commented on add.php
> +        if (validateFilled('title') === false){
Тут и далее: Функция уже возвращает `true`/`false`, нет смысла сравнивать её с `false`, можно писать так
```
if (!validate...) {
  return "...";
}
```

2021-01-18 12:28 UTC, IlyaPer commented on add.php
> +            $lot['url'] = $file_path;
Оно используется ниже, в строке 83 для расположения элементов из формы в правильном порядке

2021-01-20 05:04 UTC, nkolosov commented on add.php
> +            $lot['url'] = $file_path;
Не вижу использования `$lot` ниже по коду (тем более, мой комментарий уже на строке 84), скопируй целиком сюда

2021-01-22 10:07 UTC, nkolosov commented on add.php
> +             $lot['lot-img'] = "Ошибка загрузки фото!";
Это значение нигде не используется (т.к. после вызова `die` работа скрипта завершится.

2021-01-22 10:15 UTC, nkolosov commented on templates/add.php
> +                      <?php if ($cat['id'] == getPostVal('category_id')): ?>selected<?php endif; ?>><?=$cat['name']; ?></option>
Везде нужно использовать строго сравнение (`===`)

2021-01-25 05:16 UTC, merged