Первая попытка
htmlacademy-php/1525665-yeticave-12 pull request #9
Opened 2020-07-14 12:51 UTC by IlyaPer

2020-07-14 12:53 UTC, IlyaPer commented on main.php
> +                      <div class="lot__timer timer" <?php if($add_class === 1){
Вот здесь не понимаю, как связать $add_class из function.php с условием в main.php. По идее же add_class находится во внутренней области функции.

2020-07-14 12:57 UTC, IlyaPer commented on function.php
> +    $hours_count = date_interval_format($diff, '%H');
Теперь функция выводит вот такие значения.
![Снимок экрана 2020-07-14 в 15 56 48](https://user-images.githubusercontent.com/62990147/87428210-ab966200-c5ea-11ea-8573-78020841fad0.png)

2020-07-15 04:45 UTC, nkolosov requested changes

2020-07-15 04:45 UTC, nkolosov commented on main.php
> +                      <div class="lot__timer timer" <?php if($add_class === 1){
Функция должна возвращать массив из двух элементов, первый элемент - число часов, второе - минут.
А уже тут должно проверяться, что число часов - ноль и добавляться соответствующий класс.

Ну и одного HTML-тега не может быть несколько аттрибутов `class`, новый класс должен добавляться к уже существующему

2020-07-15 04:45 UTC, nkolosov commented on function.php
> +    $hours_count = date_interval_format($diff, '%H');
Функция date_create принимает строкой текущую дату в определенных форматах, таким образом у тебя получается не очень корректный `today`

Тебе достаточно удалить строку `$today = date("Y-m-d");`

2020-07-16 12:45 UTC, IlyaPer commented on function.php
> +    $today = date_create(date("Y-m-d"));
Если в date_create не указывать  date("Y-m-d"), то выводится ошибка.

2020-07-16 12:48 UTC, IlyaPer commented on main.php
> +                      <div class="lot__timer timer <?php if ($hours_count < 1){ echo ' timer--finishing'; }; ?>" >
Класс добавляется успешно, но при любом значении `$hours_count`. Отсюда я делаю вывод, что в работе функции есть какая-то ошибка и она выводит всегда нули. Наверное, из-за проблем с `$today`.

2020-07-24 09:34 UTC, nkolosov requested changes

2020-07-24 09:34 UTC, nkolosov commented on main.php
> +                      if ($result < 1){
1. Функцию `timer_2` нужно переименовать, название функции должно отражать то, что она делает, такое название ни о чем не говорит
2. Вызов функции и сохранение результата в переменную лучше сделать где-то выше, в начале цикла, а тут оставить только `if` с добавлением класса
3. Сравнение неверное, нужно проверять именно значение часов, а тут с `1` сравнивается весь массив, получается что-то такое `if (array(23, 55) < 1) {`, что неправильно

2020-07-24 09:34 UTC, nkolosov commented on main.php
> +                          <?=  $rest_time = implode(":", timer_2($product['date']));
Не нужно повторно вызывать функцию с тем же аргументом, ведь результат её работы уже есть в переменной `$result`

2020-07-25 02:05 UTC, nkolosov requested changes

2020-07-25 02:05 UTC, nkolosov commented on function.php
> +    $rest_time = ["hours" => $hours_count, $minutes_count];
Не нужно здесь указывать индекс строкой. К элементу массива после вызова функции можно обратиться по числовому индексу ($result[0])

2020-07-25 02:05 UTC, nkolosov commented on function.php
> +    $rest_time = ["hours" => $hours_count, $minutes_count];
Иначе, в функции `implode` порядок не будет определен и первым элементом могут стать минуты

2020-07-27 04:44 UTC, merged